### ISSUE TITLE
Problem Connecting to Replica Sets?

### ISSUE THREAD

**Issue by droppedoncaprica** [azat-co/mongoui#23]
Seems that I can't get the config set correctly to connect to a replica set.

I can properly connect to a local non-replica MongoDB database, however when I put in replica set information it fails with `not authorized for query on <db_set_in_config>.system.namespaces`

Failing replica config:

```
{
  "database": {
    "default": {
      "host": "<db1_url>,<db2_url>",
      "port": 27017,
      "name": "<db_set>",
      "username": "<username>",
      "password": "<password>"
    }
  }
}
```

Working Non-Replica Config:

```
{
  "database": {
    "default": {
      "host": "localhost",
      "port": 27017,
      "name": "some_database",
      "username": "",
      "password": ""
    }
  }
}
```

Anyone else run into this issue?

**Comment by danielo515** [comment]
Why don't just use the official mongodb driver?

**Comment by azat-co** [comment]
@danielo515 by now probably we should... but if monk is still working, then there are 3 other priorities before refactors

@droppedoncaprica please see https://github.com/azat-co/mongoui/pull/47 if it solved the issue. closing for now.
