### ISSUE TITLE
Doesn't Use Credentials Set in config.json

### ISSUE THREAD

**Issue by droppedoncaprica** [azat-co/mongoui#24]
Correct me if I'm wrong, but I can't find that being set when figuring out the connection string for Monk.

[Looking at where the config is used](https://github.com/azat-co/mongoui/blob/master/index.js#L6), I don't see them used.  Am I wrong?  

Somewhat related to #23, however judging by what I'm seeing  Monk will need to be updated for that to be supported.

**Comment by azat-co** [comment]
@droppedoncaprica FYI https://github.com/azat-co/mongoui/pull/47
