### ISSUE TITLE
Collections named with "." missing full name

### ISSUE THREAD

**Issue by AndyScott77** [azat-co/mongoui#29]
If you have a collections that contain "." the collection selection dropdown only renders the name upto the "." char.

For example, if I have a collections named :

- `Foo.Bar`
- `Foo.Baz`

The collection drop down lists : 

- `Foo`
- `Foo`

**Comment by AndyScott77** [comment]
Here's a patch that fixes the issue


[mongoui-dbname.patch.zip](https://github.com/azat-co/mongoui/files/218680/mongoui-dbname.patch.zip)

**Comment by azat-co** [comment]
@AndyScott77 thank you, but there's a brand new version of MongoUI now. I rebuild it with React and Express, no Derby anymore because that was giving me a hard time
