### ISSUE TITLE
react peer dependency issues

### ISSUE THREAD

**Issue by kantha-girish** [azat-co/mongoui#33]
`npm WARN package.json mongoui@2.0.1 No license field.
npm WARN deprecated highlight@0.2.4: Not maintained anymore
npm WARN peerDependencies The peer dependency react@^0.14.0 included from redux-devtools will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN optional dep failed, continuing fsevents@1.0.11
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.11
npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-bootstrap@0.29.1 wants react@>=0.14.0
npm ERR! peerinvalid Peer react-copy-to-clipboard@4.1.0 wants react@^0.14 || ^15
npm ERR! peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
npm ERR! peerinvalid Peer react-redux@4.4.1 wants react@^0.14.0 || ^15.0.0-rc.1
npm ERR! peerinvalid Peer redux-devtools@3.1.1 wants react@^0.14.0
`

**Comment by azat-co** [comment]
@kantha-girish what steps are you doing? what npm version do you have?

**Comment by kantha-girish** [comment]
I have cloned the repo and ran `npm install`. The error log also lists the versions of npm and node. 
Listing them down here though,
npm - 2.15.1
node - 4.4.3

**Comment by azat-co** [comment]
@kantha-girish, please try npm 3.x and node 4 or better 6.x

**Comment by kantha-girish** [comment]
@azat-co It was the version of npm. I upgraded to 3.x and it worked fine. Thanks.
