### ISSUE TITLE
baseUrl auto or in config

### ISSUE THREAD

**Issue by ludoo0d0a** [azat-co/mongoui#42]
Please, do not hardcode the baseurl

``` js
let baseUrl = 'http://localhost:3001'
```

use relative url or at least, a config file. 
Thx

**Comment by MPeli** [comment]
localhost:3001 is hardcoded in bundle.js. It is very difficult to use with an own domain.

**Comment by ludoo0d0a** [comment]
I don't understand why you put this config in your own package.json.
On each upgrade, this file will be overriden and custom config lost.
Please use another file like 'settings.json'
